import os
import random
from typing import Dict, Any

class PredictiveEngine:
    def __init__(self):
        self.models_dir = "models"
        self.cardio_model_path = os.path.join(self.models_dir, "cardio_model.pkl")
        self.renal_model_path = os.path.join(self.models_dir, "renal_model.pkl")
        
        self.cardio_model = None
        self.renal_model = None
        
        self.load_models()
        
    def load_models(self):
        """
        Attempts to load the .pkl or .h5 models generated by the Jupyter Notebooks.
        If they do not exist yet, it will gracefully fallback to a mock prediction engine
        until the user trains and saves their models into the backend/models/ directory.
        """
        if not os.path.exists(self.models_dir):
            os.makedirs(self.models_dir, exist_ok=True)
            
        try:
            import joblib
            if os.path.exists(self.cardio_model_path):
                self.cardio_model = joblib.load(self.cardio_model_path)
                print("Cardiovascular Predictive Model loaded successfully.")
                
            if os.path.exists(self.renal_model_path):
                self.renal_model = joblib.load(self.renal_model_path)
                print("Renal Predictive Model loaded successfully.")
        except ImportError:
            print("joblib not installed. Cannot load .pkl models. Falling back to Mock predictions.")
        except Exception as e:
            print(f"Error loading models: {e}. Falling back to Mock predictions.")

    def predict_cardiovascular(self, vitals: Dict[str, Any]) -> Dict[str, Any]:
        """
        Expected vitals: age, sys_bp, dia_bp, cholesterol, heart_rate
        """
        if self.cardio_model:
            # Here we would format vitals into a numpy array / dataframe and call predict()
            # e.g. prediction = self.cardio_model.predict_proba([[vitals['age'], ...]])
            pass
            
        # Mock logic based on clinical thresholds
        age = float(vitals.get("age", 50))
        sys_bp = float(vitals.get("sys_bp", 120))
        cholesterol = float(vitals.get("cholesterol", 200))
        
        risk_score = 0.0
        if age > 60: risk_score += 0.2
        if sys_bp > 140: risk_score += 0.4
        if cholesterol > 240: risk_score += 0.3
        
        risk_score += random.uniform(0.0, 0.1) # add slight variance
        risk_score = min(0.99, max(0.01, risk_score))
        
        return {
            "risk_score": round(risk_score, 2),
            "risk_category": "High" if risk_score > 0.6 else "Moderate" if risk_score > 0.3 else "Low",
            "message": "Model generated from Jupyter Notebooks not detected. This is a mock prediction based on clinical thresholds." if not self.cardio_model else "Prediction generated by AI model.",
            "recommendations": [
                "Monitor blood pressure regularly.",
                "Consult with a cardiologist regarding lipid management." if cholesterol > 200 else "Maintain a heart-healthy diet."
            ]
        }

    def predict_renal(self, vitals: Dict[str, Any]) -> Dict[str, Any]:
        """
        Expected vitals: age, creatinine, egfr, diabetes
        """
        if self.renal_model:
            pass
            
        # Mock logic based on clinical thresholds
        egfr = float(vitals.get("egfr", 90))
        creatinine = float(vitals.get("creatinine", 1.0))
        diabetes = str(vitals.get("diabetes", "no")).lower() == "yes"
        
        risk_score = 0.0
        if egfr < 60: risk_score += 0.5
        if creatinine > 1.2: risk_score += 0.3
        if diabetes: risk_score += 0.15
        
        risk_score += random.uniform(0.0, 0.05)
        risk_score = min(0.99, max(0.01, risk_score))
        
        return {
            "risk_score": round(risk_score, 2),
            "risk_category": "High" if risk_score > 0.6 else "Moderate" if risk_score > 0.3 else "Low",
            "message": "Model generated from Jupyter Notebooks not detected. This is a mock prediction based on clinical thresholds." if not self.renal_model else "Prediction generated by AI model.",
            "recommendations": [
                "Schedule a follow-up nephrology consult." if egfr < 60 else "Maintain adequate hydration.",
                "Strict glycemic control is necessary to prevent nephropathy." if diabetes else "Continue healthy lifestyle."
            ]
        }
