import os
import random
from typing import Dict, Any

class PredictiveEngine:
    def __init__(self):
        self.models_dir = "models"
        self.cardio_model_path = os.path.join(self.models_dir, "cardio_model.pkl")
        self.renal_model_path = os.path.join(self.models_dir, "renal_model.pkl")
        
        self.cardio_model = None
        self.renal_model = None
        
        self.load_models()
        
    def load_models(self):
        """
        Attempts to load the .pkl or .h5 models generated by the Jupyter Notebooks.
        If they do not exist yet, it will gracefully fallback to a mock prediction engine
        until the user trains and saves their models into the backend/models/ directory.
        """
        if not os.path.exists(self.models_dir):
            os.makedirs(self.models_dir, exist_ok=True)
            
        try:
            import joblib
            if os.path.exists(self.cardio_model_path):
                self.cardio_model = joblib.load(self.cardio_model_path)
                print("Cardiovascular Predictive Model loaded successfully.")
                
            if os.path.exists(self.renal_model_path):
                self.renal_model = joblib.load(self.renal_model_path)
                print("Renal Predictive Model loaded successfully.")
        except ImportError:
            print("joblib not installed. Cannot load .pkl models. Falling back to Mock predictions.")
        except Exception as e:
            print(f"Error loading models: {e}. Falling back to Mock predictions.")

    def predict_cardiovascular(self, vitals: Dict[str, Any]) -> Dict[str, Any]:
        """
        Expected vitals: age, sys_bp, dia_bp, cholesterol, heart_rate
        """
        age = float(vitals.get("age", 50))
        sys_bp = float(vitals.get("sys_bp", 120))
        dia_bp = float(vitals.get("dia_bp", 80))
        cholesterol = float(vitals.get("cholesterol", 200))
        heart_rate = float(vitals.get("heart_rate", 75))
        
        if self.cardio_model:
            import pandas as pd
            features = pd.DataFrame([[age, sys_bp, cholesterol, heart_rate]], 
                                    columns=["age", "trestbps", "chol", "thalach"])
            # Get probability of class 1 (High Risk)
            risk_score = float(self.cardio_model.predict_proba(features)[0][1])
            is_mock = False
        else:
            # Mock fallback if models deleted
            risk_score = 0.0
            if age > 60: risk_score += 0.2
            if sys_bp > 140: risk_score += 0.4
            if cholesterol > 240: risk_score += 0.3
            risk_score = min(0.99, max(0.01, risk_score))
            is_mock = True
        
        return {
            "risk_score": round(risk_score, 2),
            "risk_category": "High" if risk_score > 0.6 else "Moderate" if risk_score > 0.3 else "Low",
            "message": "Model generated from Jupyter Notebooks not detected. Using mock." if is_mock else "Prediction generated by Scikit-Learn AI model.",
            "recommendations": [
                "Monitor blood pressure regularly.",
                "Consult with a cardiologist regarding lipid management." if cholesterol > 200 else "Maintain a heart-healthy diet."
            ]
        }

    def predict_renal(self, vitals: Dict[str, Any]) -> Dict[str, Any]:
        """
        Expected vitals: age, creatinine, egfr, diabetes
        """
        age = float(vitals.get("age", 50))
        egfr = float(vitals.get("egfr", 90))
        creatinine = float(vitals.get("creatinine", 1.0))
        diabetes_val = str(vitals.get("diabetes", "no")).lower()
        diabetes = 1 if diabetes_val == "yes" else 0
        
        if self.renal_model:
            import pandas as pd
            features = pd.DataFrame([[age, creatinine, diabetes]], 
                                    columns=["age", "sc", "dm"])
            # Get probability of class 1 (High Risk)
            risk_score = float(self.renal_model.predict_proba(features)[0][1])
            is_mock = False
        else:
            risk_score = 0.0
            if egfr < 60: risk_score += 0.5
            if creatinine > 1.2: risk_score += 0.3
            if diabetes == 1: risk_score += 0.15
            risk_score = min(0.99, max(0.01, risk_score))
            is_mock = True
        
        return {
            "risk_score": round(risk_score, 2),
            "risk_category": "High" if risk_score > 0.6 else "Moderate" if risk_score > 0.3 else "Low",
            "message": "Model generated from Jupyter Notebooks not detected. Using mock." if is_mock else "Prediction generated by Scikit-Learn AI model.",
            "recommendations": [
                "Schedule a follow-up nephrology consult." if egfr < 60 else "Maintain adequate hydration.",
                "Strict glycemic control is necessary to prevent nephropathy." if diabetes else "Continue healthy lifestyle."
            ]
        }
