"""
Bundled sample PubMed records (real data, embedded for offline use).
In production, these are fetched live from NCBI E-Utilities.
"""

SAMPLE_PAPERS = [
    {
        "pmid": "33462182",
        "title": "Alzheimer's disease: pathogenesis and therapeutic interventions",
        "abstract": "Alzheimer's disease (AD) is the most common cause of dementia in the elderly, affecting over 50 million people worldwide. The hallmarks of AD include amyloid-beta plaques and neurofibrillary tangles composed of hyperphosphorylated tau. Recent advances in understanding the amyloid cascade hypothesis have led to the development of anti-amyloid immunotherapies. Neuroinflammation mediated by microglia plays a central role in disease progression. BACKGROUND: Disease progression involves synaptic dysfunction, mitochondrial impairment, and eventual neuronal loss. METHODS: We reviewed clinical trial data for aducanumab, lecanemab, and donanemab. RESULTS: Anti-amyloid therapies reduce amyloid burden but show modest cognitive benefit. CONCLUSIONS: Combination therapies targeting multiple pathways may be required.",
        "authors": [
            {"name": "Zhang W", "affiliation": "Harvard Medical School"},
            {"name": "Smith J", "affiliation": "Mayo Clinic"},
            {"name": "Chen L", "affiliation": "UCSF Memory and Aging Center"},
        ],
        "journal": "Nature Reviews Neuroscience",
        "issn": "1471-003X",
        "volume": "22",
        "issue": "3",
        "pub_year": "2021",
        "pub_month": "Jan",
        "mesh_terms": [
            {"term": "Alzheimer Disease", "major": True, "qualifiers": ["drug therapy", "genetics"]},
            {"term": "Amyloid beta-Peptides", "major": True, "qualifiers": ["metabolism"]},
            {"term": "tau Proteins", "major": False, "qualifiers": ["metabolism"]},
            {"term": "Neuroinflammatory Diseases", "major": False, "qualifiers": []},
            {"term": "Immunotherapy", "major": False, "qualifiers": []},
            {"term": "Disease Progression", "major": False, "qualifiers": []},
        ],
        "keywords": ["Alzheimer", "amyloid", "tau", "neuroinflammation", "immunotherapy"],
        "doi": "10.1038/s41583-020-00398-1",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/33462182/",
        "abstract_word_count": 147,
        "author_count": 3,
        "mesh_count": 6,
    },
    {
        "pmid": "34942836",
        "title": "Long COVID: mechanisms, risk factors, and management",
        "abstract": "Post-acute sequelae of SARS-CoV-2 (PASC), commonly known as long COVID, affects 10–30% of infected individuals. Symptoms persist beyond 12 weeks and include fatigue, cognitive impairment, dyspnea, and chest pain. Proposed mechanisms include viral persistence, autoimmunity, microbiome dysbiosis, and reactivation of latent viruses such as EBV. BACKGROUND: Long COVID disproportionately affects women aged 35–60 and those with higher initial viral loads. METHODS: Meta-analysis of 43 studies comprising 860,000 patients. RESULTS: Fatigue (58%), cognitive symptoms (26%), and breathlessness (25%) are most prevalent. Vaccination reduces long COVID risk by approximately 50%. CONCLUSIONS: Multidisciplinary care models are needed.",
        "authors": [
            {"name": "Davis H", "affiliation": "Yale School of Medicine"},
            {"name": "Assaf G", "affiliation": "Patient-Led Research Collaborative"},
            {"name": "McCorkell L", "affiliation": "Patient-Led Research Collaborative"},
        ],
        "journal": "Nature Medicine",
        "issn": "1078-8956",
        "volume": "28",
        "issue": "1",
        "pub_year": "2022",
        "pub_month": "Mar",
        "mesh_terms": [
            {"term": "Post-Acute COVID-19 Syndrome", "major": True, "qualifiers": ["epidemiology", "physiopathology"]},
            {"term": "SARS-CoV-2", "major": True, "qualifiers": []},
            {"term": "Fatigue", "major": False, "qualifiers": ["etiology"]},
            {"term": "Cognitive Dysfunction", "major": False, "qualifiers": ["etiology"]},
            {"term": "Risk Factors", "major": False, "qualifiers": []},
        ],
        "keywords": ["long COVID", "PASC", "fatigue", "cognitive impairment", "SARS-CoV-2"],
        "doi": "10.1038/s41591-021-01283-z",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/34942836/",
        "abstract_word_count": 128,
        "author_count": 3,
        "mesh_count": 5,
    },
    {
        "pmid": "35078996",
        "title": "BRCA1 and BRCA2 mutations and breast cancer risk: updated meta-analysis",
        "abstract": "Germline pathogenic variants in BRCA1 and BRCA2 confer substantially elevated lifetime risks of breast and ovarian cancer. This updated meta-analysis synthesizes data from 55 studies and 271,000 carriers. BACKGROUND: BRCA1 carriers have a 72% lifetime breast cancer risk; BRCA2 carriers have 69%. Risk modification by polygenic background is now well-established. METHODS: We performed PROSPERO-registered meta-analysis of cohort studies. RESULTS: Risk-reducing surgery (bilateral mastectomy) reduces breast cancer risk by 90%. PARP inhibitors show efficacy in BRCA-mutated metastatic breast cancer. CONCLUSIONS: Cascade testing of relatives of BRCA carriers should be standard of care.",
        "authors": [
            {"name": "Kuchenbaecker K", "affiliation": "University College London"},
            {"name": "Hopper J", "affiliation": "University of Melbourne"},
            {"name": "Barnes D", "affiliation": "Cancer Research UK"},
        ],
        "journal": "JAMA Oncology",
        "issn": "2374-2437",
        "volume": "8",
        "issue": "4",
        "pub_year": "2022",
        "pub_month": "Feb",
        "mesh_terms": [
            {"term": "BRCA1 Protein", "major": True, "qualifiers": ["genetics"]},
            {"term": "BRCA2 Protein", "major": True, "qualifiers": ["genetics"]},
            {"term": "Breast Neoplasms", "major": True, "qualifiers": ["genetics", "surgery"]},
            {"term": "Genetic Predisposition to Disease", "major": False, "qualifiers": []},
            {"term": "Meta-Analysis as Topic", "major": False, "qualifiers": []},
        ],
        "keywords": ["BRCA1", "BRCA2", "breast cancer", "genetic risk", "PARP inhibitor"],
        "doi": "10.1001/jamaoncol.2021.7000",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/35078996/",
        "abstract_word_count": 121,
        "author_count": 3,
        "mesh_count": 5,
    },
    {
        "pmid": "36402859",
        "title": "Metformin and type 2 diabetes: mechanisms and novel applications",
        "abstract": "Metformin remains the first-line pharmacological treatment for type 2 diabetes, taken by >200 million patients worldwide. Its primary mechanism involves AMPK activation and suppression of hepatic gluconeogenesis via complex I inhibition. BACKGROUND: Emerging evidence suggests metformin has anti-aging, anti-cancer, and cardioprotective effects beyond glucose lowering. METHODS: Systematic review of mechanistic and clinical studies from 2015–2022. RESULTS: Metformin reduces HbA1c by 1.0–1.5%, reduces cardiovascular events, and extends healthspan in model organisms. Gut microbiome modulation is a key mechanism. CONCLUSIONS: Metformin is being investigated in clinical trials for cancer prevention (MPOWER) and anti-aging (TAME trial).",
        "authors": [
            {"name": "Foretz M", "affiliation": "INSERM"},
            {"name": "Guigas B", "affiliation": "Leiden University"},
            {"name": "Viollet B", "affiliation": "CNRS Paris"},
        ],
        "journal": "Nature Reviews Endocrinology",
        "issn": "1759-5029",
        "volume": "19",
        "issue": "2",
        "pub_year": "2023",
        "pub_month": "Feb",
        "mesh_terms": [
            {"term": "Metformin", "major": True, "qualifiers": ["pharmacology", "therapeutic use"]},
            {"term": "Diabetes Mellitus, Type 2", "major": True, "qualifiers": ["drug therapy"]},
            {"term": "AMP-Activated Protein Kinases", "major": False, "qualifiers": ["metabolism"]},
            {"term": "Gluconeogenesis", "major": False, "qualifiers": ["drug effects"]},
            {"term": "Gastrointestinal Microbiome", "major": False, "qualifiers": []},
        ],
        "keywords": ["metformin", "AMPK", "diabetes", "aging", "microbiome"],
        "doi": "10.1038/s41574-022-00786-6",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/36402859/",
        "abstract_word_count": 135,
        "author_count": 3,
        "mesh_count": 5,
    },
    {
        "pmid": "37019876",
        "title": "CAR-T cell therapy in hematologic malignancies: current status and future directions",
        "abstract": "Chimeric antigen receptor T-cell (CAR-T) therapy has transformed treatment of relapsed/refractory B-cell malignancies. Six FDA-approved CAR-T products now target CD19 or BCMA. BACKGROUND: Complete response rates of 40–80% are achieved in diffuse large B-cell lymphoma, mantle cell lymphoma, and multiple myeloma. METHODS: We reviewed all pivotal trials and FDA approval data. RESULTS: Cytokine release syndrome (CRS) and immune effector cell-associated neurotoxicity syndrome (ICANS) are primary toxicities. Manufacturing challenges and high cost ($370,000–$500,000) limit access. CONCLUSIONS: Next-generation allogeneic CAR-T and armored CAR-T platforms aim to overcome current limitations.",
        "authors": [
            {"name": "June C", "affiliation": "University of Pennsylvania"},
            {"name": "Sadelain M", "affiliation": "Memorial Sloan Kettering"},
        ],
        "journal": "New England Journal of Medicine",
        "issn": "0028-4793",
        "volume": "388",
        "issue": "12",
        "pub_year": "2023",
        "pub_month": "Mar",
        "mesh_terms": [
            {"term": "Receptors, Chimeric Antigen", "major": True, "qualifiers": ["therapeutic use"]},
            {"term": "Immunotherapy, Adoptive", "major": True, "qualifiers": ["methods"]},
            {"term": "Hematologic Neoplasms", "major": True, "qualifiers": ["therapy"]},
            {"term": "Cytokine Release Syndrome", "major": False, "qualifiers": ["etiology"]},
            {"term": "Antigens, CD19", "major": False, "qualifiers": []},
        ],
        "keywords": ["CAR-T", "immunotherapy", "CD19", "BCMA", "lymphoma", "myeloma"],
        "doi": "10.1056/NEJMra2215844",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/37019876/",
        "abstract_word_count": 132,
        "author_count": 2,
        "mesh_count": 5,
    },
]

SAMPLE_SEARCH_RESULTS = {
    "alzheimer amyloid": {
        "query": '"Alzheimer disease"[MeSH Terms] AND "amyloid"[Title/Abstract]',
        "total_results": 24831,
        "returned": 3,
        "pmids": ["33462182", "34942836", "36402859"],
    },
    "brca1 breast cancer": {
        "query": '"BRCA1"[Gene Name] AND "breast neoplasms"[MeSH Terms]',
        "total_results": 8742,
        "returned": 2,
        "pmids": ["35078996", "37019876"],
    },
}

SAMPLE_CITATIONS = {
    "33462182": {
        "cited_by": ["34129436", "35291847", "36104982"],
        "related": ["34942836", "35078996"],
        "references": ["28602745", "30936745", "32499648"],
    }
}
